# Generated by Django 2.2 on 2023-03-24 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='prodt',
            new_name='prod',
        ),
    ]
